<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <AssemblyName>doob.SignalARRR.Server</AssemblyName>
    <RootNamespace>doob.SignalARRR.Server</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bernhard Windisch</Authors>
    <Company>-</Company>
    <Description></Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/doob-at/SignalARRR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/doob-at/SignalARRR</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>doob.SignalARRR.Server</PackageId>
    <Product>doob.SignalARRR.Server</Product>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ImpromptuInterface" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="NamedServices.Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="doob.Reflectensions.Json" />
    <PackageReference Include="doob.Reflectensions.Invoke" />
    <PackageReference Include="doob.Reflectensions.CommonExtensions" />
    <PackageReference Include="System.Reactive.Linq" />
    
    <PackageReference Include="System.Interactive.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignalARRR.Common\SignalARRR.Common.csproj" />
    <ProjectReference Include="..\SignalARRR.ProxyGenerator\SignalARRR.ProxyGenerator.csproj" />
  </ItemGroup>

</Project>
