<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <AssemblyName>doob.SignalARRR.Common</AssemblyName>
    <RootNamespace>doob.SignalARRR.Common</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bernhard Windisch</Authors>
    <Company>-</Company>
    <Description></Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/doob-at/SignalARRR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/doob-at/SignalARRR</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>doob.SignalARRR.Common</PackageId>
    <Product>doob.SignalARRR.Common</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
