<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="doob.Reflectensions" Version="6.2.1-beta0013" />
    <PackageVersion Include="doob.Reflectensions.CommonExtensions" Version="6.4.2" />
    <PackageVersion Include="doob.Reflectensions.ExpandableObject" Version="6.2.1-beta0013" />
    <PackageVersion Include="doob.Reflectensions.Invoke" Version="6.4.2" />
    <PackageVersion Include="doob.Reflectensions.Json" Version="6.4.2" />
    <PackageVersion Include="ImpromptuInterface" Version="8.0.6" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="9.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="9.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="NamedServices.Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Serilog.AspNetCore" Version="4.1.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageVersion Include="System.Interactive.Async" Version="6.0.1" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="System.Reactive.Linq" Version="6.0.1" />
    <PackageVersion Include="System.Threading.Channels" Version="9.0.4" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.0" />
  </ItemGroup>
</Project>